### ISSUE TITLE
Request for a Jupyter file with step-by-step explanation or simple example

### ISSUE THREAD

**Issue by nahomtse** [fteicht/gnn4rcpsp#6]
Dear Florent,

I hope this message finds you well. I have been actively using your repository, for my project, and I must say it has been a valuable resource. However, as I dive deeper into the codebase, I find myself in need of additional guidance to fully understand the implementation details.

**Comment by nahomtse** [comment]
I'm unable to reproduce the results you get

**Comment by fteicht** [comment]
Dear Nahom,
Sorry for the delay, I was on long leave during the summer. Do you still need a notebook to guide you or at least a Readme explaining how to run the different scripts and in which order? I know I must provide such a Readme when I will have a little time to do so.
Thanks for your interest in this library,
Florent

**Comment by nahomtse** [comment]
Hi Florent, thank you for your reply.
I am able to the run the code. However transferring multi mode RCPSP instead of single mode RCPSP in to the code FOR SIREN does not seem to work as I tried multiple options and routes to make a proper graph representation. Perhaps If you can make guide or jupyter file to implement that, it would be very useful!

Kind regards,
Nahom

**Comment by fteicht** [comment]
I'm glad to hear that you could finally find your way in our scripts despite the lack of documentation!
Multi-Mode RCPSPs are quite different in nature to Single Mode RCPSPs (the only ones that are handled in our code at the moment). It is not obvious which GNN architecture can properly capture their structure. We identified it as a future line of research. We would happy to collaborate with you on this if you have some ideas you'd like share with us :-)
Kind regards,
Florent
