### ISSUE TITLE
Also applicable for MM?

### ISSUE THREAD

**Issue by nahomtse** [fteicht/gnn4rcpsp#7]
Dear Florent,

I hope this message finds you well. I have been actively using your repository, for my project, and I must say it has been a valuable resource. However, as I dive deeper into the codebase, I find myself in need of additional guidance to fully understand the implementation details.

**Comment by fteicht** [comment]
Sure. As mentioned in issue #6 I must provide a detailed Readme on how to use this repository's scripts.
